import { typecho_contents } from "@prisma/client";
import dayjs from "dayjs";
import type { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import "dayjs/locale/zh-cn";
import Calendar from "dayjs/plugin/Calendar";
import { getPostsList } from "./api/posts";
import { useState } from "react";

dayjs.locale("zh-cn");
dayjs.extend(Calendar);

export const getStaticProps: GetStaticProps<{ posts: typecho_contents[] }, {}> =
	async () => {
		const posts = await getPostsList({});
		return {
			props: {
				posts,
			},
			revalidate: 10000,
		};
	};

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = (
	props
) => {
	const [pageIndex, setPageIndex] = useState(1);
	const [posts, setPosts] = useState(props.posts);
	const loadMore = async () => {
		fetch(
			"/api/posts?" +
				new URLSearchParams({ page: (pageIndex + 1).toString() })
		)
			.then((res) => res.json())
			.then((json) => {
				setPageIndex(pageIndex + 1);
				setPosts([...posts, ...json.list]);
			});
	};
	return (
		<div className={"md:p-4 min-h-screen"}>
			<Head>
				<title>博客</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main
				className={
					"flex flex-col justify-center items-center p-4 overflow-hidden bg-gray-200 border rounded-lg dark:bg-gray-700 dark:border-gray-600"
				}>
				<div className={"w-full max-w-screen-md space-y-4"}>
					{posts.map((post) => {
						return (
							<div
								key={post.cid}
								className="min-w-full px-8 py-4 mx-auto bg-white rounded-lg shadow-md dark:bg-gray-800">
								<div className="flex items-center justify-between">
									<span className="text-sm font-light text-gray-600 dark:text-gray-400">
										{post.modified &&
											dayjs
												.unix(post.modified)
												.calendar(null, {
													sameDay: "[今天] h:mm A", // The same day ( Today at 2:30 AM )
													nextDay: "[明天]", // The next day ( Tomorrow at 2:30 AM )
													nextWeek: "dddd", // The next week ( Sunday at 2:30 AM )
													lastDay: "[昨天]", // The day before ( Yesterday at 2:30 AM )
													lastWeek: "[上周] dddd", // Last week ( Last Monday at 2:30 AM )
													sameElse: "YYYY/DD/MM", // Everything else ( 7/10/2011 )
												})}
									</span>
									<a className="px-3 py-1 text-sm font-bold text-gray-100 transition-colors duration-200 transform bg-gray-600 rounded cursor-pointer hover:bg-gray-500">
										Code
									</a>
								</div>

								<div className="mt-2 ">
									<Link href={`/${post.cid}`}>
										<a
											href="#"
											className="block truncate text-2xl font-bold text-gray-700 dark:text-white hover:text-gray-600 dark:hover:text-gray-200 hover:underline"
											dangerouslySetInnerHTML={{
												__html: post.title || "",
											}}
										/>
									</Link>
									<p className="mt-2 text-gray-600 dark:text-gray-300">
										{post.slug}
									</p>
								</div>

								<div className="flex items-center justify-between mt-4">
									<Link href={`/${post.cid}`}>
										<a
											href="#"
											className="text-blue-600 dark:text-blue-400 hover:underline">
											Read more
										</a>
									</Link>

									<div className="flex items-center">
										<div className="relative w-10 h-10 mx-4 rounded-full sm:block">
											<Image
												className="hidden object-cover "
												src="/favicon.ico"
												alt="avatar"
												layout="fill"
											/>
										</div>

										<a className="font-bold text-gray-700 cursor-pointer dark:text-gray-200">
											zkl2333
										</a>
									</div>
								</div>
							</div>
						);
					})}

					<div
						onClick={loadMore}
						className="w-max mx-auto text-center px-4 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-200 transform bg-indigo-600 rounded-md hover:bg-indigo-500 focus:outline-none focus:ring focus:ring-indigo-300 focus:ring-opacity-80">
						加载更多
					</div>
				</div>
			</main>
		</div>
	);
};

export default Home;
