import { PrismaClient, typecho_contents } from "@prisma/client";
import type { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const prisma = new PrismaClient();

export const getStaticProps: GetStaticProps<{ posts: typecho_contents[] }, {}> =
	async () => {
		try {
			const typecho_contents = await prisma.typecho_contents.findMany({
				where: { type: "post" },
			});
			// console.log(typecho_contents);
			return {
				props: {
					posts: typecho_contents,
				},
				revalidate: 10000,
			};
		} catch (error) {
			await prisma.$disconnect();
			return {
				notFound: true,
			};
		}
	};

const Home = ({ posts }: InferGetStaticPropsType<typeof getStaticProps>) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<div className={styles.grid}>
					{posts.map((post) => {
						return (
							<Link key={post.cid} href={`/${post.cid}`}>
								<a className={styles.card}>
									<h2>{post.title} &rarr;</h2>
									<p>{post.slug}</p>
								</a>
							</Link>
						);
					})}
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer">
					Powered by{" "}
					<span className={styles.logo}>
						<Image
							src="/vercel.svg"
							alt="Vercel Logo"
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
