import { PrismaClient, typecho_contents } from "@prisma/client";
import type { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import "tailwindcss/tailwind.css";

const prisma = new PrismaClient();

export const getStaticProps: GetStaticProps<{ posts: typecho_contents[] }, {}> =
	async () => {
		try {
			const typecho_contents = await prisma.typecho_contents.findMany({
				where: { type: "post", status: "publish" },
				take: 10,
				orderBy: {
					created: "desc",
				},
			});
			return {
				props: {
					posts: typecho_contents,
				},
				revalidate: 10000,
			};
		} catch (error) {
			await prisma.$disconnect();
			return {
				notFound: true,
			};
		}
	};

const Home = ({ posts }: InferGetStaticPropsType<typeof getStaticProps>) => {
	return (
		<div className={"px-8"}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main
				className={
					"min-h-screen flex flex-col justify-center items-center flex-1 pt-16 pb-4 my-4 overflow-hidden bg-gray-200 border rounded-lg dark:bg-gray-700 dark:border-gray-600"
				}>
				<h1 className={"mb-12 text-7xl"}>
					Welcome to{" "}
					<a
						className="text-blue-700 hover:text-purple-600 focus:text-purple-600 visited:text-purple-600"
						href="https://nextjs.org">
						Next.js!
					</a>
				</h1>

				<div className={styles.grid}>
					{posts.map((post) => {
						return (
							<div
								key={post.cid}
								className="min-w-full px-8 py-4 mb-4 mx-auto bg-white rounded-lg shadow-md dark:bg-gray-800">
								<div className="flex items-center justify-between">
									<span className="text-sm font-light text-gray-600 dark:text-gray-400">
										Mar 10, 2019
									</span>
									<a className="px-3 py-1 text-sm font-bold text-gray-100 transition-colors duration-200 transform bg-gray-600 rounded cursor-pointer hover:bg-gray-500">
										Design
									</a>
								</div>

								<div className="mt-2 ">
									<a
										href="#"
										className="truncate text-2xl font-bold text-gray-700 dark:text-white hover:text-gray-600 dark:hover:text-gray-200 hover:underline">
										{post.title}
									</a>
									<p className="mt-2 text-gray-600 dark:text-gray-300">
										{post.slug}
									</p>
								</div>

								<div className="flex items-center justify-between mt-4">
									<Link href={`/${post.cid}`}>
										<a
											href="#"
											className="text-blue-600 dark:text-blue-400 hover:underline">
											Read more
										</a>
									</Link>

									<div className="flex items-center">
										<div className="w-10 h-10 mx-4 rounded-full sm:block">
											<Image
												className="hidden object-cover "
												src="/favicon.ico"
												alt="avatar"
												width="40"
												height="40"
											/>
										</div>

										<a className="font-bold text-gray-700 cursor-pointer dark:text-gray-200">
											zkl2333
										</a>
									</div>
								</div>
							</div>
							// /* //{" "}
							// 		<h2 className="truncate">
							// 			// {post.title} &rarr; //{" "}
							// 		</h2>
							// 		// <p>{post.slug}</p> */
						);
					})}
				</div>
			</main>
		</div>
	);
};

export default Home;
